modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
license = "Insert License Here"

[[mods]]
modId = "effective"
version = "${version}"
displayName = "${name}"
description = '''
${description}
'''

[[mixins]]
config = "effective-common.mixins.json"

[[mixins]]
config = "effective.mixins.json"

[[dependencies.effective]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.effective]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.effective]]
modId = "velvet"
type = "optional"
versionRange = "[0.4,)"
ordering = "NONE"
side = "CLIENT"